version: '3.6'
services:
  medex:
    image: medex:latest
    ports:
      - "8000:8000"
    depends_on:
      - database_medex
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database_medex
    volumes:
      - ./import:/app/import
    restart: always

  database_medex:
    image: postgres
    shm_size: 1g
    ports:
      - "127.0.0.1:5429:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    restart: always
# Uncomment if you want the database to survive a recration of the database container
#    volumes:
#      - ./data:/var/lib/postgresql/data
